FROM python:3

# install phantomjs
RUN mkdir -p /opt/phantomjs \
        && cd /opt/phantomjs \
        && wget -O phantomjs.tar.bz2 https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 \
        && tar xavf phantomjs.tar.bz2 --strip-components 1 \
        && ln -s /opt/phantomjs/bin/phantomjs /usr/local/bin/phantomjs \
        && rm phantomjs.tar.bz2

# install pyspider
RUN pip install --no-cache-dir  pyspider

WORKDIR /root
VOLUME ["/root"]
ENTRYPOINT ["pyspider"]

EXPOSE 5000 23333 24444 25555

