FROM ubuntu:16.04

RUN  sed -i 's/security.ubuntu/mirrors.aliyun/g' /etc/apt/sources.list\
	&&  sed -i 's/archive.ubuntu/mirrors.aliyun/g' /etc/apt/sources.list\
	&& apt update\
	&& apt install -y openssh-server\
	&& echo "root:123" | chpasswd 
RUN useradd ider\
	&& echo "ider:123" | chpasswd\
	&& rm -rf /var/lib/apt/lists/*
ENTRYPOINT service ssh start;bash

